# This workflow deploys the static site to GitHub Pages
#
# It triggers on pushes to the main branch.

name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a recent LTS version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build # Replace with your build command, e.g., 'npm run build', 'gulp build', etc.
        env:
          BASE_URL: ${{ github.event.repository.name }} # Set base URL for relative paths if needed

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire build directory
          path: './dist' # Replace with your build output directory, e.g., 'dist', 'build', etc.

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3