name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Build and deploy to GitHub Pages
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_URL: ${{ github.repository_url }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@${REPOSITORY_URL}.git
          git push --force origin main:gh-pages

      # Update GitHub Pages URL in repository settings
      - name: Update GitHub Pages URL
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.repos.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pages: {
                cname: '',
                source: {
                  branch: 'gh-pages',
                  path: '/'
                }
              }
            })